name: Build & Push Image

on:
  # Run this workflow from other workflows
  workflow_call:
    inputs:
      repo_name:
        description: 'Name of app repo for Docker image'
        required: true
        type: string
      commit_id:
        description: 'HEAD commit hash'
        required: true
        type: string
      file:
        description: 'The dockerfile to build the image against'
        required: false
        default: 'Dockerfile'
        type: string
      latest:
        description: 'Tag the image with latest?'
        required: false
        default: false
        type: boolean
      build_args:
        description: 'build-args to docker'
        required: false
        default: ''
        type: string

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: zooniverse/${{ inputs.repo_name }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Create registry tags
      id: create_tags
      run: |
        tag="ghcr.io/zooniverse/${{ inputs.repo_name }}:${{ inputs.commit_id }}"
        if [ "${{ inputs.latest }}" = true ]; then tag="$tag,ghcr.io/zooniverse/${{ inputs.repo_name }}:latest"; fi
        echo $tag
        echo "tag=$tag" >> $GITHUB_OUTPUT

    - name: Create commit_id.txt
      run: echo ${{ inputs.commit_id }} > commit_id.txt

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ inputs.file }}
        push: true
        tags: ${{ steps.create_tags.outputs.tag }}
        build-args: ${{ inputs.build_args }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
