name: Build & Push Image

on:
  # Run this workflow from other workflows
  workflow_call:
    inputs:
      repo_name:
        description: 'Name of app repo for Docker image'
        required: true
        type: string
      commit_id:
        description: 'HEAD commit hash'
        required: true
        type: string
      latest:
        description: 'Tag the image with latest?'
        required: false
        default: false
        type: boolean

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Create registry tags
      id: create_tags
      run: |
        tag="ghcr.io/zooniverse/${{ inputs.repo_name }}:${{ inputs.commit_id }}"
        if [ "${{ inputs.latest }}" = true ]; then tag="$tag,ghcr.io/zooniverse/${{ inputs.repo_name }}:latest"; fi
        echo $tag
        echo ::set-output name=tag::$tag

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.create_tags.outputs.tag }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
