name: Deploy Static

on:
  # Run this workflow from other workflows
  workflow_call:
    inputs:
      source:
        description: 'Source package'
        required: true
        type: string
      target:
        description: 'Path to target folder'
        required: true
        type: string
      max_age:
        description: 'max-age for non-index.html files'
        default: 604800
        required: false
        type: string
    secrets:
      creds:
        required: true

jobs:
  deploy_static:
    runs-on: ubuntu-latest
    steps:
    - name: Download source
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.source }}

    - uses: azure/login@v2
      with:
        creds: ${{ secrets.creds }}

    - name: Upload to blob storage
      id: upload
      uses: azure/CLI@v2
      with:
        azcliversion: 2.33.1
        inlineScript: |
          az storage blob upload \
            --account-name zooniversestatic \
            --content-cache-control 'public, max-age=60' \
            --container-name '$web' \
            --name '${{ inputs.target }}/index.html' \
            --file './index.html'
          rm ./index.html
          az storage blob upload \
            --account-name zooniversestatic \
            --content-cache-control 'public, max-age=60' \
            --container-name '$web' \
            --name '${{ inputs.target }}/commit_id.txt' \
            --file './commit_id.txt'
          rm ./commit_id.txt
          az storage blob upload-batch \
            --account-name zooniversestatic \
            --content-cache-control 'public, immutable, max-age=${{ inputs.max_age }}' \
            --destination '$web/${{ inputs.target }}' \
            --source ./
