name: NPM build

on:
  # Run this workflow from other workflows
  workflow_call:
    inputs:
      commit_id:
        description: 'HEAD commit hash'
        required: true
        type: string
      node_version:
        default: 'lts/hydrogen'
        description: 'Node version'
        required: false
        type: string
      script:
        description: 'npm build script'
        required: true
        type: string
      output:
        description: 'Output directory name'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HEAD_COMMIT: ${{ inputs.commit_id }}
    steps:
    - uses: actions/checkout@v4.1.1

    - name: Node.js build
      id: build
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'npm'
    - run: npm ci --ignore-scripts
    - run: npm run ${{ inputs.script }}

    - name: Write commit_id.txt
      run: echo ${HEAD_COMMIT} > ./${{ inputs.output }}/commit_id.txt

    - name: Save build
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.output }}
        path: ./${{ inputs.output }}/
