name: Test Lambda Deployment

on:
  pull_request:
  workflow_dispatch:

jobs:
  test_lambda_deploy:
    name: Deploy to AWS
    uses: ./.github/workflows/deploy_lambda_function.yaml
    with:
      function: 'cicd-test-lambda'
      directory: 'lambda-deploy-test'
