name: Test Azure Uploads

on:
  pull_request:
  workflow_dispatch:

jobs:
  build_files:
    runs-on: ubuntu-latest
    steps:
    - name: Create test files
      run: |
        echo "<!doctype html><html lang="en"><head><title>Testing HTML Pages</title></head><body><p>This is some html!</p></body></html>" > index.html
        echo "3e8245739f934e71ef0ea21730086875a084c093" > commit_id.txt
        echo "console.log()" > javascript.js
        curl --output zoologobw.jpg https://raw.githubusercontent.com/zooniverse/Brand/master/style%20guide/logos/zooniverse-emblem/zooniverse-logo-black.jpg
        curl --output zoologoteal.png https://raw.githubusercontent.com/zooniverse/Brand/master/style%20guide/logos/zooniverse-emblem/zooniverse-logo-teal.png

    - name: Save build
      uses: actions/upload-artifact@v4
      with:
        name: upload-test
        path: .

  upload_test:
    name: Upload to blob storage
    uses: ./.github/workflows/deploy_static.yaml
    needs: build_files
    with:
      source: 'upload-test'
      target: 'upload-test'
    secrets:
      creds: ${{ secrets.AZURE_STATIC_SITES }}

  delete_test:
    name: Delete from blob storage
    uses: ./.github/workflows/delete_blobs.yaml
    needs: upload_test
    with:
      target: 'upload-test'
    secrets:
      creds: ${{ secrets.AZURE_STATIC_SITES }}
