name: Test Azure Uploads

on:
  pull_request:
  workflow_dispatch:

jobs:
  test_uploads:
    runs-on: ubuntu-latest
    steps:
    - name: Create test files
      run: |
        echo "<!doctype html><html lang="en"><head><title>Testing HTML Pages</title></head><body><p>This is some html!</p></body></html>" > index.html
        echo "3e8245739f934e71ef0ea21730086875a084c093" > commit_id.txt
        echo "console.log()" > javascript.js
        curl --output zoologobw.jpg https://raw.githubusercontent.com/zooniverse/Brand/master/style%20guide/logos/zooniverse-emblem/zooniverse-logo-black.jpg
        curl --output zoologoteal.png https://raw.githubusercontent.com/zooniverse/Brand/master/style%20guide/logos/zooniverse-emblem/zooniverse-logo-teal.png

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_STATIC_SITES }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az version
          az storage blob upload \
            --account-name zooniversestatic \
            --content-cache-control 'public, max-age=60' \
            --container-name '$web' \
            --name 'uploadtest/index.html' \
            --file './index.html'
          rm ./index.html
          az storage blob upload \
            --account-name zooniversestatic \
            --content-cache-control 'public, max-age=60' \
            --container-name '$web' \
            --name 'uploadtest/commit_id.txt' \
            --file './commit_id.txt'
          rm ./commit_id.txt
          az storage blob upload-batch \
            --account-name zooniversestatic \
            --content-cache-control 'public, immutable, max-age=604800' \
            --destination '$web/uploadtest' \
            --source ./
