name: Test Lambda Deployment

on:
  pull_request:
  workflow_dispatch:

jobs:
  build_files:
    runs-on: ubuntu-latest
    steps:
    - name: Create Lambda test script
      run: |
        mkdir -p lambda-upload-test
        cat <<EOF > lambda-upload-test/cicd-test-lambda.py
        import requests
        def lambda_handler(event, context):
            print("Executing test lambda function.")
            return {
                'statusCode': 200,
                'body': 'Success'
            }
        EOF

    - name: Deploy to AWS
      uses: ./.github/workflows/deploy_lambda_function.yaml
      with:
        function: 'cicd-test-lambda'
        directory: 'lambda-upload-test'
